name: Check types and build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --frozen-lockfile
      - run: bun run type-check
      - run: bun format-check
      - run: bun test
      - run: bun run build-ci
      - run: bunx publint --strict
